### PR TITLE
Link Fixes and Formatting Adjustments/Corrections

### PR DESCRIPTION
**Pull request by FreeWillyB**
1. Fixed broken image links for NEMS Branding by moving images to _static folder, since they weren't being moved in the build process.
2. Added "sphinx_notfound_page" extension to fix broken 404.html resource URI's when not in the root directory since resources were hardcoded as "_static/". The extension changes the URI to "/en/latest/_static" (or whatever language/version you are on), so the formatting remains the same.
3. Fixed a broken link on Changelog 1.2
4. Fixed a couple broken links on the NEMS commands page
5. Corrected several formatting inconsistencies and cleared up all the "WARNING" messages that were experienced during the build process.

### CODE REVIEW

**Comment by Cat5TV** [comment]
Superb! Thank you!

**Comment by Cat5TV** [comment]
Failing to build on readthedocs, looks like an issue with the 404 changes.

```
Running Sphinx v1.8.5
loading translations [en]... done

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/nemslinux/envs/latest/lib/python3.7/site-packages/sphinx/registry.py", line 472, in load_extension
    mod = __import__(extname, None, None, ['setup'])
ModuleNotFoundError: No module named 'notfound'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/nemslinux/envs/latest/lib/python3.7/site-packages/sphinx/cmd/build.py", line 303, in build_main
    args.tags, args.verbosity, args.jobs, args.keep_going)
  File "/home/docs/checkouts/readthedocs.org/user_builds/nemslinux/envs/latest/lib/python3.7/site-packages/sphinx/application.py", line 228, in __init__
    self.setup_extension(extension)
  File "/home/docs/checkouts/readthedocs.org/user_builds/nemslinux/envs/latest/lib/python3.7/site-packages/sphinx/application.py", line 449, in setup_extension
    self.registry.load_extension(self, extname)
  File "/home/docs/checkouts/readthedocs.org/user_builds/nemslinux/envs/latest/lib/python3.7/site-packages/sphinx/registry.py", line 475, in load_extension
    raise ExtensionError(__('Could not import extension %s') % extname, err)
sphinx.errors.ExtensionError: Could not import extension notfound.extension (exception: No module named 'notfound')

Extension error:
Could not import extension notfound.extension (exception: No module named 'notfound')
```

Any guesses? I know I'd had issues with the 404 pages when I first set them up, hence the way the problem you detected (I had to makeshift).

Thanks  :)

**Comment by FreeWillyB** [comment]
> Failing to build on readthedocs, looks like an issue with the 404 changes.
> 
> ```
> Running Sphinx v1.8.5
> loading translations [en]... done
> 
> Traceback (most recent call last):
>   File "/home/docs/checkouts/readthedocs.org/user_builds/nemslinux/envs/latest/lib/python3.7/site-packages/sphinx/registry.py", line 472, in load_extension
>     mod = __import__(extname, None, None, ['setup'])
> ModuleNotFoundError: No module named 'notfound'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/home/docs/checkouts/readthedocs.org/user_builds/nemslinux/envs/latest/lib/python3.7/site-packages/sphinx/cmd/build.py", line 303, in build_main
>     args.tags, args.verbosity, args.jobs, args.keep_going)
>   File "/home/docs/checkouts/readthedocs.org/user_builds/nemslinux/envs/latest/lib/python3.7/site-packages/sphinx/application.py", line 228, in __init__
>     self.setup_extension(extension)
>   File "/home/docs/checkouts/readthedocs.org/user_builds/nemslinux/envs/latest/lib/python3.7/site-packages/sphinx/application.py", line 449, in setup_extension
>     self.registry.load_extension(self, extname)
>   File "/home/docs/checkouts/readthedocs.org/user_builds/nemslinux/envs/latest/lib/python3.7/site-packages/sphinx/registry.py", line 475, in load_extension
>     raise ExtensionError(__('Could not import extension %s') % extname, err)
> sphinx.errors.ExtensionError: Could not import extension notfound.extension (exception: No module named 'notfound')
> 
> Extension error:
> Could not import extension notfound.extension (exception: No module named 'notfound')
> ```
> 
> Any guesses? I know I'd had issues with the 404 pages when I first set them up, hence the way the problem you detected (I had to makeshift).
> 
> Thanks :)

I’m not sure how you’re hosting, but I had install a python package using “pip install sphinx-notfound-page” when locally hosting. 

The problems I had was when that on the main level of the site (I.e. “/en/latest/“), any 404 error resulted in the 404.html page with the expected formatting. However, the css references were listed as “_static/css/theme.css”, so it’s relative to the current directory. If the 404 happens in another directory, (I.e. “/en/latest/directory/“) the style pages is no longer found and all formatting disappears. 

Python Module
https://pypi.org/project/sphinx-notfound-page/

Expected 404
https://docs.nemslinux.com/en/latest/foo.html

No Formatting
https://docs.nemslinux.com/en/latest/foo/bar.html

**Comment by FreeWillyB** [comment]
That module basically just corrects the references to the static folder from the relative path of “_static” to the absolute path “/en/latest/_static”

**Comment by FreeWillyB** [comment]
Just found this on RTD. Looks like you just need to add the module to the requirements.txt file. 


https://docs.readthedocs.io/en/stable/guides/specifying-dependencies.html

**Comment by Cat5TV** [comment]
The hosting is via https://readthedocs.org/ - you can setup a test build environment yourself if you like, which will let you see it as I see it.

Did you want to make the changes you mention and create a new PR?

Thanks!

**Comment by FreeWillyB** [comment]
Didn’t realize that was an option. I’ll look into it later this week.

**Comment by Cat5TV** [comment]
Hi @FreeWillyB have you had a chance to review your changes so we can re-compile? Thanks!

**Pull request merged**
